# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

[en-ph]

[ja]
  title = "愛と関係"
  [ja.params]
    description = "実りある関係と無条件の愛の秘密を解き明かします。"      # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ko]
  title = "사랑과관계"
  [ko.params]
    description = "결실을 맺는 관계와 무조건적인 사랑의 비밀을 푸십시오."      # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
