### Info: https://gohugo.io/content-management/multilingual/#configure-languages

#[en]
  #languageName = "English"
  #languageFlag = "ğŸ‡¬ğŸ‡§"
  #languageCode = "en"
  #languageCodeCountry = "DO_NOT_USE"
  #timeZone = "Etc/UTC"
  #weight = 110

[en-ph]
  languageName = "English (PH)"
  languageFlag = "ğŸ‡µğŸ‡­"
  languageCode = "en-PH"
  languageCodeCountry = "ph"
  timeZone = "Asia/Manila"
  weight = 111

#[fil]
  #languageName = "Filipino"
  #languageFlag = "ğŸ‡µğŸ‡­"
  #languageCode = "fil"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 120
  #title = ""
  #[fil.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[tl-tglg]
  #languageName = "Tagalog Baybayin"
  #languageFlag = "ğŸ‡µğŸ‡­"
  #languageCode = "tl-Tglg"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 121
  #title = ""
  #[tl.tglg.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hant]
  #languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³"
  #languageCode = "zh-Hant"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 130
  #title = ""
  #[zh-hant.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hans]
  #languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³"
  #languageCode = "zh-Hans"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 131
  #title = ""
  #[zh-hans.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ja]
  languageName = "æ—¥æœ¬èª"
  languageFlag = "ğŸ‡¯ğŸ‡µ"
  languageCode = "ja"
  languageCodeCountry = "jp"
  timeZone = "Asia/Tokyo"
  weight = 140
  title = "æ„›ã¨é–¢ä¿‚"
  [ja.params]
    description = "å®Ÿã‚Šã‚ã‚‹é–¢ä¿‚ã¨ç„¡æ¡ä»¶ã®æ„›ã®ç§˜å¯†ã‚’è§£ãæ˜ã‹ã—ã¾ã™ã€‚"      # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ko]
  languageName = "í•œêµ­ì–´"
  languageFlag = "ğŸ‡°ğŸ‡·"
  languageCode = "ko"
  languageCodeCountry = "kr"
  timeZone = "Asia/Seoul"
  weight = 150
  title = "ì‚¬ë‘ê³¼ ê´€ê³„"
  [ko.params]
    description = "ê²°ì‹¤ì„ ë§ºëŠ” ê´€ê³„ì™€ ë¬´ì¡°ê±´ì ì¸ ì‚¬ë‘ì˜ ë¹„ë°€ì„ í‘¸ì‹­ì‹œì˜¤."      # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
